language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --dev

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
